before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: OmHgbZ/x5GhjouBxnx61zTUabYMS3+hS70rqtOg7OFU8FTBJvVBsfbd14C55e9kdGYgiLpb+8nuTzd0cJBk9uZztMtsr9/GhK9kgx/RxqBlBoUF2FhW6FNpdJZEBbgl09S/A8JQhAtqd8+xO6/y3bONdN/KefhGhjgKHEdPOpJMC4qddNyrV29dJTJ+AOfc0CIMQ6WBDnFRsJlPlvQYZJmgFofqOQhjdLcBf8MgZH/K3gFxJ3M4VQeoyStgRaKANuTvh+M1MdsyEXddwtEYRLUKiJxxdcCghqeqpFvBlql3YWTXmvnGZeoe/SyLbujlnJ6xAEad6+oeLkTd7syDY0LeILdgsBZxyIXS/PERZNVUv6TFVFZgsql7WgIVIbPtoQwNU2UZWSaEENy5Xo8OjwzrFjT/P0SoYVYIpEedNHoekEY6THf7CZhYbo+rVkl4n8hgLzXSRLuQ2PbpF17NB568RI+acOxqkTZXcitFP/8iVEeMpiwsdT0WtiADMBVI3tS04XL0FrgJ8HWYDU1KrJxMy0QJua/QY5tEvKM+2gm7XJ9YlHfRcBI0G0Zt+mlVcSwEBOv7z391uK0ZwPOfVuak/AzTXXKw/Pr6zEVNYpE7nXnV36Z6B1Kb4bsG0N3NvP820sc7KK4K73kbHjX/nrpMp3mudTUOSimYhTAf9hpU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
